Alta coesao e baixo acoplamento
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #140
Opened 2021-09-05 02:56 UTC by francisco1code

## Descrição
PR destinado ao desenvolvimento do tópicos GRASPs - Polimorfismo.

#131

2021-09-05 13:25 UTC, DanielPortods commented
Esse pr precisa ser direcionado à branch doc/131_main

2021-09-05 13:51 UTC, DanielPortods requested changes
🔍

2021-09-05 13:51 UTC, DanielPortods commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;Antes de falamos de [baixo acoplamento](#baixo-acoplamento), primeiro vamos falar de acoplamento, oque é acoplamento? É uma forma medir o quão um elemento está conectado a outro elemento,
2x "OQUE é acoplamento", "OQUE é um baixo acoplamento"

2021-09-05 13:51 UTC, DanielPortods commented on docs/padroes-de-projeto/grasp.md
> +
Não seria: "já conhecidoS PELA leteratura" ?

2021-09-05 13:51 UTC, DanielPortods commented on docs/padroes-de-projeto/grasp.md
> +* Dificuldades em entender os elementos isoladamentes.
Isoladamente*

2021-09-05 13:51 UTC, DanielPortods commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;Para responder à pergunta feita no início desse tópico, achamos a seguinte resposta, "Tenta balancear a atribuição de responsabilidade e dependência entre os elementos, para que tenha um
Esse "a" não tem crase.
A resposta seria: "TentaR  balancear a atribuição de responsabilidadeS e dependênciaS entre os elementos, para que tenhaM um baixo acoplamento". Note que faltou o fechamento das aspas.

2021-09-05 13:51 UTC, DanielPortods commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;Pensado nisso a maioria das nossas decisões para nossa aplicação, foram munidas com esses princípios dita pela literatura, assim conseguimos chegar em um objetivo limpo e claro, norteado
[...]principios DITOS pela literatura[...].
Sempre colocar "GRASP" em capslock por se tratar de um acrônimo.

2021-09-06 14:23 UTC, francisco1code commented
@DanielPortods  Todos os erros foram resolvidos. Desde já muito Obrigado pelo feedback!!! Vou tentar ficar mais atento com esses erros.

2021-09-07 01:14 UTC, DanielPortods commented
> Esse pr precisa ser direcionado à branch doc/131_main

Esse PR continua direcionado à branh main.

2021-09-08 16:29 UTC, DanielPortods approved these changes
🏆

2021-09-08 16:39 UTC, Bruno-Felix commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;No projeto de software, uma qualidade básica conhecida como coesão mede informalmente como funcionalidades relacionam as operações de um elemento de software e também mede quanto trabalho
"fazer uso DO BOAS práticas de software" escrita errada

2021-09-08 16:39 UTC, Bruno-Felix commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;Um dos grandes problemas relacionado ao planejamento de um grande projeto está atrelado a seguinte pergunta, "Como criar uma aplicação com baixa dependência, baixo impacto de mudança e ma
a literatura ABORTA o tema

2021-09-08 16:41 UTC, Bruno-Felix commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;Antes de falamos de [baixo acoplamento](#baixo-acoplamento), primeiro vamos falar de acoplamento, é uma forma medir o quão um elemento está conectado a outro elemento, tem conhecimento de
"OQUE é acoplamento fica mais fácil descrever OQUE é um baixo acoplamento"

2021-09-08 16:42 UTC, Bruno-Felix commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;Para deixa o contexto mais rico iremos falar sobre alto acoplamento, no  caso seria um elemento que depende de muitos outros elementos, assim acarretando alguns problemas já conhecido pel
"Para DEIXAR..." erro de escrita

2021-09-08 16:43 UTC, Bruno-Felix commented on docs/padroes-de-projeto/grasp.md
> +&emsp;&emsp;Pensado nisso a maioria das nossas decisões para nossa aplicação, foram munidas com esses princípios dita pela literatura, assim conseguimos chegar em um objetivo limpo e claro, norteado
"PENSADO nisso..." erro de escrita

2021-09-08 18:18 UTC, Joao-Pedro-Moura commented
Erros corrigidos. Obrigado pela revisão!

2021-09-09 12:09 UTC, Bruno-Felix approved these changes
Boa!!

2021-09-09 12:09 UTC, merged