Doc/131 main
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #148
Opened 2021-09-10 18:34 UTC by omateusp

## Descrição
Documento de GRAPs

Verificar se todos os hiperlinks estão adicionados e funcionando

## _Issue_ Relacionada
Close #131

2021-09-10 19:03 UTC, enzoggqs requested changes

2021-09-10 19:03 UTC, enzoggqs commented on docs/padroes-de-projeto/grasp.md
> +Um malefício claro desse padrão é quando a solução sugerida pelo especialista não é desejável, o que pode acontecer em algumas situações, mas os benefícios são inquestionáveis: baixo acoplamento, o e
Acho que aqui teria que linkar as palavras "baixo acoplamento" com o tópico baixo acoplamento

2021-09-10 19:03 UTC, enzoggqs commented on docs/padroes-de-projeto/grasp.md
> +|1.8|04/09/2021| Adição da controlador e variações protegidas | Enzo Gabriel e Edson Araújo |
o versionamento pula do 1.6 pro 1.8

2021-09-10 19:03 UTC, enzoggqs commented on docs/padroes-de-projeto/grasp.md
> +## Bibliografia
pular uma linha para a ##Bibliografia

2021-09-11 18:40 UTC, enzoggqs approved these changes
massa!

2021-09-11 19:43 UTC, edsondearaujo approved these changes
Após as mudanças dos pontos observados pelo @enzoggqs. Está tudo certo com a documentação.

2021-09-11 21:16 UTC, merged