Doc/147 pacotes
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #156
Opened 2021-09-13 17:14 UTC by omateusp

## Descrição
Revisão do diagrama de pacotes, adição da v2.0

## _Issue_ Relacionada
Close #147

2021-09-14 12:31 UTC, DanielPortods requested changes

2021-09-14 12:31 UTC, DanielPortods commented on docs/modelagem/modelagem-estatica/diagrama-de-pacotes.md
> +<center>[Figura 1: Diagrama de pacotes 1.0](../../assets/imagens/diagrama-de-pacotes/Diagrama-de-pacotes.png)</center>
essa é a figura 2.

2021-09-14 12:32 UTC, DanielPortods commented
No front tem uma seta estranha sainda do diretório components, está correta?

2021-09-14 12:35 UTC, DanielPortods commented
As direções das setas Models --> Controllers, Middlewares --> Controllers e Database --> Node.js estão corretas ? É relação de dependência?

2021-09-14 12:40 UTC, DanielPortods commented
O Diagrama do Back tá muito diferente do que consta no repositório do back-end. Tem diretório faltando, não existe um Node.js e sim src...
Precisa ajustar isso aí pra ficar coerente com o repositório.

2021-09-20 10:55 UTC, enzoggqs approved these changes

2021-09-20 11:22 UTC, DanielPortods approved these changes
🏆

2021-09-20 11:22 UTC, merged