Review sprint 5
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #157
Opened 2021-09-13 22:31 UTC by enzoggqs

## Descrição
Foi criado o documento da review da sprint 5

## _Issue_ Relacionada
#149

2021-09-14 12:20 UTC, DanielPortods commented
Esse velocity tá mostrando informações desnecessárias e fora do padrão. A gente usa somente as sprints das milestones.

2021-09-14 12:25 UTC, DanielPortods commented
Não existe o caso de issues serem documentadas sem posntuação. Verificar o que houve com a pontuação das #146 e #147 e checar se está tudo correto no zenhub.

2021-09-14 13:06 UTC, gabrielbpn requested changes
Me parece que faltam os GOFS Criacionais na listagem das issues.
Considere como débito técnico também.

2021-09-14 18:28 UTC, enzoggqs commented
> Esse velocity tá mostrando informações desnecessárias e fora do padrão. A gente usa somente as sprints das milestones.

@DanielPortods Tentei aqui, mas não sei como filtra os dados do velocity nao

2021-09-14 21:13 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint5.md
> +5. **Issue:** [#150 GOFS Comportamentais](https://github.com/UnBArqDsw2021-1/2021.1_G6_Curumim/issues/150)<br>
Nome errado. Aqui são os "GOFS Criacionais"

2021-09-14 21:14 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint5.md
> +### **Débitos técnicos para a Sprint 6**
Faltou adicionar os GOFS Criacionais aqui nos débitos técnicos.

2021-09-14 21:17 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint5.md
> +|  1.1   | 13/09/2021 | Finalização do documento | Enzo Gabriel |
Adiciona o nome dos revisores aqui no versionamento.

2021-09-19 18:10 UTC, Bruno-Felix approved these changes
Me parece ok. Boa!!

2021-09-20 01:31 UTC, francisco1code approved these changes
LGTM

2021-09-20 11:14 UTC, merged