GOFs Estruturais - Composite
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #160
Opened 2021-09-14 04:45 UTC by Joao-Pedro-Moura

## Descrição
PR para adição do tópico de composite 

## _Issue_ Relacionada
#145

2021-09-14 12:09 UTC, DanielPortods requested changes
🔍

2021-09-14 12:09 UTC, DanielPortods commented on docs/padroes-de-projeto/gofs-estruturais.md
> +<center>[Figura 2: Board Composite](../../assets/imagens/gofs/composite-codigo.png)</center>
O link da imagem está quebrado por conta do .png

2021-09-14 12:14 UTC, DanielPortods commented
Nas diretrizes para terceira entrega, a professora solicita a apresentação dos padrões em nível de modelagem também. Sendo assim, seria interessante ter um recorte do diagrama de classes onde se pode verificar a utilização do padrão.

2021-09-14 12:14 UTC, DanielPortods commented
Falta: 
- [ ] Resolver os conflitos.

2021-09-14 19:14 UTC, Joao-Pedro-Moura commented
> Nas diretrizes para terceira entrega, a professora solicita a apresentação dos padrões em nível de modelagem também. Sendo assim, seria interessante ter um recorte do diagrama de classes onde se pode verificar a utilização do padrão.

O diagrama de classes atual está desatualizado. Então no diagrama atual não temos o Composite ainda e teremos que mudar algumas coisas no diagrama para utilizá-lo.

2021-09-15 00:50 UTC, DanielPortods commented
> > Nas diretrizes para terceira entrega, a professora solicita a apresentação dos padrões em nível de modelagem também. Sendo assim, seria interessante ter um recorte do diagrama de classes onde se pode verificar a utilização do padrão.
> 
> O diagrama de classes atual está desatualizado. Então no diagrama atual não temos o Composite ainda e teremos que mudar algumas coisas no diagrama para utilizá-lo.

A ideia seria criar um recorte novo de como funcionará o padrão no escopo do projet e utilizando as nossas classes. Mesmo não tendo no diagrama de classes.

2021-09-19 17:38 UTC, Joao-Pedro-Moura commented
Recorte do diagrama de classes colocado.

2021-09-19 23:56 UTC, omateusp approved these changes
Tirando os erros que já estavam no documento, tá ok pra mim.

2021-09-20 04:42 UTC, DanielPortods approved these changes
🏆

2021-09-20 04:42 UTC, merged