Revisão do diagrama de classes
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #172
Opened 2021-09-19 23:06 UTC by DanielPortods

## Descrição

Foram adicionadas classes conforme decidido para os padrões de projetos bem como corrigidos alguns aspectos referentes ao feedback.

## _Issue_ Relacionada

#161

2021-09-19 23:39 UTC, omateusp requested changes
Erros de ortografia, de resto parece ok pra mim

2021-09-19 23:39 UTC, omateusp commented on docs/modelagem/modelagem-estatica/diagrama-de-classes.md
>  &emsp;&emsp;O desenvolvimento do diagrama de classes levou em consideração as decisões de técnologias e estruturas que serão utilizadas no projeto. Sendo assim, o diagrama de classes aborda a represe
"técnologias" deveria ser tecnologias, erro de ortografia

2021-09-19 23:39 UTC, omateusp commented on docs/modelagem/modelagem-estatica/diagrama-de-classes.md
> +&emsp;&emsp;A seguir temos a segunda versão do diagrama de classes, o qual foi aprimorado conforme o feedback da segunda entrega e os ajustes necessários apó as escolhas dos padrões de projetos<br>
"apó" deveria ser após, erro de ortografia

2021-09-19 23:39 UTC, omateusp commented on docs/modelagem/modelagem-estatica/diagrama-de-classes.md
>  - A maioria dos métodos das classes controllers tem relação de dependencia com a classe AuthController, tais relações não foram incluídas no diagrama para facilitar a visualização.
"dependencia" deveria ser dependência, erro de ortografia

2021-09-20 08:26 UTC, omateusp approved these changes
LGTM

2021-09-20 11:32 UTC, edsondearaujo reviewed
Buscar adicionar citações de referencias no embasamento teórico.
Buscar incluir pelo menos mais uma bibliografia.

2021-09-20 17:19 UTC, edsondearaujo approved these changes
LGTM

2021-09-20 17:20 UTC, merged