Revisao entrega 2
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #190
Opened 2021-09-21 23:21 UTC by NiloMendonca

## Descrição
Issue direcionada a revisão dos texto da entrega 2 segundo feedback da professora.

## _Issue_ Relacionada
Closes #161

2021-09-22 01:55 UTC, Joao-Pedro-Moura requested changes

2021-09-22 01:55 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-dinamica/casos-de-uso.md
> +&emsp;&emsp;Os diagramas de casos de uso são diagramas que fazem uso da notação UML (Unified Modeling Language) e buscam descrever as funcionalidades propostas para um determinado sistema, é consider
Falta acento na palavra "auxilio"

2021-09-22 01:55 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-dinamica/diagrama-de-sequencia.md
> +### [Guardian](/2021.1_G6_Curumim/base/requisitos/modelagem/lexicos/#lexico-responsavel) fazendo [login](/2021.1_G6_Curumim/base/requisitos/modelagem/lexicos/#lexico-login)
Links para os léxicos nas imagens estão quebrando

2021-09-22 01:55 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-estatica/DER.md
> +&emsp;&emsp;O Diagrama entidade relacionamento, também conhecido como DER, aborda uma forma de representar gráficamente a modelagem do banco de dados. Basicamente, tem como objetivo organizar de form
A palavra "Graficamente" não possui acento.

2021-09-22 01:55 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-estatica/DER.md
>  &emsp;&emsp;Para o desenvolvimento do diagrama conceitual, foi feita a leitura e analise do [MER](./MER.md) procurando elucidar gráficamente as ideias contidas no artefato. Sendo assim, o diagrama co
- Falta acento na palavra "analise"; 
- Graficamente não possui acento;
- Está escrito '"senguindo" ao invés de seguindo.

2021-09-22 01:55 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-estatica/diagrama-de-componentes.md
> +&emsp;&emsp;O desenvolvimento do diagrama de componentes levou em consideração as decisões de técnologias e estruturas que serão utilizadas no projeto. Sendo assim, o diagrama de componentes aborda a
Acentuação errada na palavra "técnologias"

2021-09-23 18:24 UTC, enzoggqs requested changes

2021-09-23 18:24 UTC, enzoggqs commented on docs/modelagem/modelagem-estatica/DER.md
> +&emsp;&emsp;O Diagrama entidade relacionamento, também conhecido como DER, aborda uma forma de representar gráficamente a modelagem do banco de dados. Basicamente, tem como objetivo organizar de form
@NiloMendonca  e @edsondearaujo isso ainda precisa de correção

2021-09-28 23:07 UTC, enzoggqs approved these changes

2021-09-28 23:38 UTC, Joao-Pedro-Moura requested changes
Só fazer essas últimas correções no diagrama de sequência e aprovo.

2021-09-28 23:38 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-dinamica/diagrama-de-sequencia.md
>  <center>[Figura 1: Diagrama de sequência do administrador cadastrando professor](../../../assets/imagens/diagrama-de-sequencia/../../../assets/imagens/diagrama-de-sequencia/Diagrama-de-sequencia-admi
Legenda da imagem está igual a da imagem anterior

2021-09-28 23:38 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-dinamica/diagrama-de-sequencia.md
> +<center>[Figura 2: Diagrama de sequência do guardian fazendo login](../../../assets/imagens/diagrama-de-sequencia/Diagrama-de-sequencia-pais-responsaveis-login.png)</center>
Esta é a figura 3 e está figura 2.

2021-09-28 23:38 UTC, Joao-Pedro-Moura commented on docs/modelagem/modelagem-dinamica/diagrama-de-sequencia.md
Léxico "Administrador" e "professor" estão quebrando

2021-09-29 01:07 UTC, Joao-Pedro-Moura approved these changes

2021-09-29 01:07 UTC, Joao-Pedro-Moura commented
Aprovado!

2021-09-29 01:07 UTC, merged