Review da sprint 7
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #195
Opened 2021-09-29 13:48 UTC by NiloMendonca

## Descrição
Adição da review da sprint 7 e inclusão da nova aba no menu referente a entrega 4.

## _Issue_ Relacionada
#194

2021-09-29 14:36 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +
Nilo, nessa parte de "Resultados", é interessante incluir também as issues que ficaram como dívida, como, por exemplo, essa issue:

https://github.com/UnBArqDsw2021-1/2021.1_G6_Curumim_Front-end/issues/7

E nessas, colocar o Status: "Dívida"

2021-09-29 14:37 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +### **Débitos técnicos para a Sprint 8**
Tenta incluir nesses débitos técnicos as issues que estão relacionadas a eles.

2021-09-29 14:38 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +### **Débitos técnicos para a Sprint 8**
De forma que ao a pessoa apertar em "Home page Professor", por exemplo, já caia na issue.

2021-09-29 14:39 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +### **Débitos técnicos para a Sprint 8**
E também colocar esse "(Front-End)" e "(Back-End) clicáveis, de forma que ao a pessoa apertar, ele caia nos respectivos repositórios do front e do back.

2021-09-29 14:40 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +- Responsável visualizar os detalhe de um evento (Front-end);
Alterar "detalhe" para "detalhes"

2021-09-29 14:40 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +- Responsável visualizar todos as anotações (Front-end);
Trocar "todos as anotações" por "todas as anotações""

2021-09-29 14:41 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +- Já iniciou a entrega das funcionalidades da aplicação;
Alterar para "já se iniciou a entrega..." ou "já iniciamos a entrega..."

2021-09-29 14:42 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +- Melhorou o trabalho em equipe entre o front-end e o back-end;
Talvez adicionar um hiperlink em "front-end" e "back-end" para, ao serem clicados, a pessoa cair nos respectivos repositórios.

2021-09-29 14:42 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +|  1.0   | 29/09/2021 | Abertura e adição da informações ao documento | Nilo Mendonça |
Adicionar revisores.

2021-09-29 14:46 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +<center>[Figura 2: Velocity Tracking gerado pelo Zenhub](../../assets/imagens/sprint-review/sprint7/velocity-tracking.png)</center>
Eu tava dando uma olhada aqui na Review da Sprint 5 (https://unbarqdsw2021-1.github.io/2021.1_G6_Curumim/reunioes/sprints/review-sprint5/) e o responsável gerou o velocity com o zenhub em modo escuro e a visualização ficou bem melhor.

Caso não te dê muito trabalho e você também achar que fica melhor pra visualizar, considera fazer isso. 
Deixando claro aqui que é só um detalhe, se der problema, não precisa.

2021-09-29 14:46 UTC, gabrielbpn requested changes
Show. Só uns detalhes a arrumar e eu aprovo!

2021-09-29 14:48 UTC, gabrielbpn commented on docs/reunioes/sprints/review-sprint7.md
> +<center>[Figura 2: Velocity Tracking gerado pelo Zenhub](../../assets/imagens/sprint-review/sprint7/velocity-tracking.png)</center>
Isso também pode ser aplicado ao Burndown, é claro.

2021-09-29 18:25 UTC, gabrielbpn approved these changes
Ótimo!

2021-09-30 01:15 UTC, DanielPortods approved these changes
Somente atualizei o burndown para retirar os prs e o velocity pra tirar a sprint 5 bugada.
Atualizei o a revisão por pares no versionamento também.
🏆

2021-09-30 01:16 UTC, merged