Documento de arquitetura - Visão de implementação
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #201
Opened 2021-10-02 18:08 UTC by NiloMendonca

## Descrição
Foi efetuada a adição dos textos referentes a visão arquitetural de implementação.

## _Issue_ Relacionada
#196 #198

2021-10-03 01:43 UTC, DanielPortods commented
Esse pr deve ter como destino a brancho do doc de arquitetura e não a branch main.

2021-10-03 04:21 UTC, francisco1code commented
@DanielPortods problema resolvido, vlw!

2021-10-04 18:19 UTC, omateusp requested changes
Apenas 2 erros de português, de resto parece ok

2021-10-04 18:19 UTC, omateusp commented on docs/arquitetura-reutilizacao/arquitetura.md
> +- Diagramas de componentes que ilustram os susbsistemas, organizados em camadas e hierarquias;
susbsistemas = subsistemas

2021-10-04 18:19 UTC, omateusp commented on docs/arquitetura-reutilizacao/arquitetura.md
> +&emsp;&emsp;Sendo considerado extremamente útil em questões relacionadas a atribuição do trabalho de implementação a indivíduos e equipes, na avaliação da quantidade de código que será excluído, modi
discursões = discussões

2021-10-05 00:17 UTC, gabrielbpn requested changes
Só umas coisinhas extras que vai ser bom incluir.

Bom trabalho, senhores!

2021-10-05 00:17 UTC, gabrielbpn commented on docs/arquitetura-reutilizacao/arquitetura.md
> +- GoFs Comportamentais (Observer)
Acho que esses tópicos acima podem ter um hiperlink como rastro para esses artefatos mencionados.

2021-10-05 00:17 UTC, gabrielbpn commented on docs/arquitetura-reutilizacao/arquitetura.md
> +&emsp;&emsp;No projeto Curumim o objetivo da divisão em camadas é possibilitar a reutilização da solução para diversas interfaces. Especificamente no back-end da aplicação a estrutura foi dividida em
Ádicionar um hiperlink no "back-end" pro repositório do back.

2021-10-05 00:17 UTC, gabrielbpn commented on docs/arquitetura-reutilizacao/arquitetura.md
> +|1.2|02/10/2021| Criando tópico de visão de implementação | Francisco Ferreira e Nilo Mendonça|
Adicionar revisores, por favor.

2021-10-05 00:17 UTC, gabrielbpn commented on docs/arquitetura-reutilizacao/arquitetura.md
> +|1.2|02/10/2021| Criando tópico de visão de implementação | Francisco Ferreira e Nilo Mendonça|
Se bem que aqui vai ter um monte de revisores, né. Melhor deixar pro último que fizer a visão. Desconsiderem

2021-10-05 22:56 UTC, francisco1code commented
Hiperlink resolvido @gabrielbpn

2021-10-05 23:30 UTC, gabrielbpn approved these changes
Show!

2021-10-06 01:17 UTC, omateusp approved these changes
LGTM

2021-10-06 01:18 UTC, merged