Padronizando e fazendo ajustes no documento de Moscow
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #26
Opened 2021-08-05 00:56 UTC by enzoggqs

## Descrição

Foi atualizado o documento de Moscow, fazendo as atualizações necessárias para a padronização do documento.

## _Issue_ Relacionada

#16

2021-08-05 05:22 UTC, DanielPortods requested changes
Seria interessante disponibilizar a planilha com link de visualização. 
Se atente também ao versionamento, notei que não foi atualizado.

2021-08-05 05:22 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/moscow.md
> +
Versionamento tá sem título.

2021-08-05 05:22 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/moscow.md
> +&emsp;&emsp;Para a classificação das prioridades dos requisitos não funcionais, os 10 integrantes do grupo fizeram um debate utilizando a plataforma Microsoft Teams e chegaram a um consenso quanto as
Esses são requisitos funcionais.

2021-08-05 05:22 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/moscow.md
Na verdade, a gente padronizou o W com sendo would. Algo do tipo: seria bom ter, poderá ser feito se sobrar tempo.

2021-08-05 11:36 UTC, enzoggqs commented on docs/base/requisitos/priorizacao/moscow.md
Mas eu pesquisei algumas coisas e vi até o vídeo disponibilizado pela professora e won't é o mais utilizado, e os Won't e Would se enquadram praticamente na mesma coisa

2021-08-05 11:36 UTC, enzoggqs commented on docs/base/requisitos/priorizacao/moscow.md
Mesmo assim permaneço como would?

2021-08-05 14:09 UTC, DanielPortods approved these changes
Show! :trophy:

2021-08-06 00:43 UTC, Bruno-Felix approved these changes
Sensacional.

2021-08-06 00:43 UTC, merged