Padronização do First Things First
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #27
Opened 2021-08-05 01:08 UTC by eliseukadesh67

## Descrição

Atualiza o documeto de First Things First, adicionando texto informativo antes da tabela, corrigindo o ID dos requisitos e padroniza melhor o documento.

## _Issue_ Relacionada
#15

2021-08-05 05:12 UTC, DanielPortods requested changes
Muitos dos pontos levantados para correção anteriormente continuam presentes. 
Para remover algumas colunas da tabela, poderia ser inserido no doc uma breve explicação sobre como são feitos os cálculos e seus parâmetros.
Além disso, é importante que a planilha fique disponível com link de visualização.

2021-08-05 05:12 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/first-things-first.md
> +A tabela a seguir detalha e identifica os requisitos funcionais que foram elicitados, seus custos, valor, risco, e também a prioridade baseada no artefato [Moscow](./moscow.md) que também foi realiza
Sem o caracter de paragrafo que foi padronizado.

2021-08-05 05:12 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/first-things-first.md
> +| RF_01 | Ter sistema de comunicação entre responsáveis e professores.                    | 6,5                | 5                 | 28          | 6,69%   | 8              | 9,47%   | 4
Pq o markdown dessa tabela tá tão bugado?

2021-08-05 05:12 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/first-things-first.md
> +| RF_03 | Responsáveis receberem notificações sobre novas atividades.                     | 7                  | 2                 | 20          | 4,78%   | 4              | 4,73%   | 5
Foi comentada que essa tabela nesse formato ficaria pouco visual na wiki. pode deixar somente as infromações mais esenciais.

2021-08-05 05:12 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/first-things-first.md
> +| 0.1    | 29/07/2021 | Reunião para decidir a priorização dos requisitos | Bruno Félix, Daniel Porto, Edson de Araújo, Eliseu Kadesh, Enzo Gabriel, Francisco Emanoel, João Pedro, Mateus Oliveira, Ga
Versionamento tá sem o título.

2021-08-05 05:12 UTC, DanielPortods commented on docs/base/requisitos/priorizacao/first-things-first.md
Não tem bibliografia.

2021-08-05 14:18 UTC, eliseukadesh67 commented
> Muitos dos pontos levantados para correção anteriormente continuam presentes.
> Para remover algumas colunas da tabela, poderia ser inserido no doc uma breve explicação sobre como são feitos

2021-08-05 16:11 UTC, eliseukadesh67 commented
@DanielPortods Você recomenda então que seja disponibilizado um link para o drive que contém a tabela do FTF que fizemos, para mais detalhamento?

2021-08-05 16:16 UTC, DanielPortods commented
Sim! se tiver alguma dúvida, acho que cê pode dar uma olhada na branch do moscow que ficou bem padronizada quanto a isso.

2021-08-06 02:07 UTC, eliseukadesh67 commented
As mudanças solicitadas foram realizadas.

2021-08-06 02:34 UTC, enzoggqs approved these changes
Boa!

2021-08-06 03:39 UTC, Bruno-Felix approved these changes
Ficou bom!!

Forças pra mãe!!

2021-08-06 03:41 UTC, DanielPortods approved these changes

2021-08-06 03:42 UTC, merged