Criação do documento de Sprint Review - Sprint 0
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #66
Opened 2021-08-11 18:37 UTC by eliseukadesh67

## Descrição

Foi adicionado o documento da Sprint Review (Revisão e Retrospectiva) da sprint 0.

## _Issue_ Relacionada

#50

2021-08-11 21:34 UTC, DanielPortods requested changes
Só esse ponto.

2021-08-11 21:34 UTC, DanielPortods commented on docs/reunioes/sprints/review-sprint0.md
> + **Status: Concluída**<br>
A Pontuação desse issue tá errada. Seria 5.

2021-08-12 00:00 UTC, eliseukadesh67 commented on docs/reunioes/sprints/review-sprint0.md
> + **Status: Concluída**<br>
Corrigido!

2021-08-12 12:26 UTC, Bruno-Felix approved these changes
Show!!

2021-08-12 12:26 UTC, merged