Doc/56 diagrama de pacote
UnBArqDsw2021-1/2021.1_G6_Curumim pull request #69
Opened 2021-08-13 02:10 UTC by francisco1code

## Descrição
Foi feito a criação do diagrama de pacotes para o projeto e a inclusão do mesmo na página do mkdocs.

## _Issue_ Relacionada
#56

2021-08-13 11:46 UTC, DanielPortods commented on docs/modelagem/modelagem-estatica/casos-de-uso.md
> +## Introdução
Algo de errado não está certo 🤔

2021-08-13 23:43 UTC, DanielPortods requested changes

2021-08-13 23:43 UTC, DanielPortods commented on mkdocs.yml
> +                        - Casos de uso: modelagem/modelagem-estatica/casos-de-uso.md
Casos de uso continua na nav.

2021-08-13 23:48 UTC, DanielPortods commented
O título do pacote inicia poderia ser o nome do projeto, não acham? Além disso, o pacote do back-end não deveria abranger o de database? 
Outra coisa... O sequelize depende dos controllers? Não seria algo mais independente em que os modelos tivessem como alterar?

2021-08-14 02:53 UTC, francisco1code commented
@DanielPortods faz total sentido, tinhas muita gaffes nessa secção do back kkkkkk, e aquele sequelize nem era para estar ali, vou providenciar essas mudanças para ontem. 

![ ](https://media.giphy.com/media/PiQejEf31116URju4V/giphy.gif)

2021-08-14 03:06 UTC, francisco1code commented on mkdocs.yml
> +                        - Casos de uso: modelagem/modelagem-estatica/casos-de-uso.md
Problema resolvido.

2021-08-14 19:13 UTC, edsondearaujo reviewed
Acho que seria uma boa usar cores para uma melhor visualização dos pacotes. Outra mudança seria, colocar o link da legenda do digrama, no modelo markdown.

![Captura de tela de 2021-08-14 16-12-51](https://user-images.githubusercontent.com/39536164/129457837-8a330ae4-3743-4714-bafe-44301138a005.png)

2021-08-14 19:24 UTC, DanielPortods commented
Isso que o @edsondearaujo comentou sobre o link realmente vai gerar um erro ao realizar o deploy. Deve-se colocar o caminha local da imagem, pois o link que está, aponta para a branch aqui revisada a qual será apagado.

2021-08-14 22:48 UTC, DanielPortods approved these changes
🏆

2021-08-15 01:54 UTC, merged